const enUS = {
  'app_title': 'KacamataMoo',
  'search_hint': 'Search glasses by name...',
  'loading': 'Loading...',
  'error': 'Error',
  'camera_permission_denied': 'Camera permission denied',
  'are_you_sure_you_want_to_logout': 'Are you sure you want to logout?',

  // Login Page
  'login':'Login',
  'login_wording': 'Please input your email and password to login',
  'email':'Email',
  'password':'Password',
  'forgot_password':'Forgot Password?',
  'please_enter_email':'Please enter your email',
  'password_warning':'Password must be at least 6 chars',
  'sign_in':'Sign In',
  'copy_right': '© 2026 KacamataMoo. All rights reserved.',

  // Home Screen
  'eye_wear_for_everyone':'Eyewear Tailored to You',
  'ai_powered':'AI-Powered Virtual Try-On System',
  'ai_help_your_style':'When AI helps your style',
  'title_menu_one':'I want a new frame',
  'sub_title_menu_one':"",
  'title_menu_two':'I want new lens',
  'sub_title_menu_two':'',
  'title_menu_three':'I want both',
  'sub_title_menu_three':'',
  'change_language':'Language',

  // Frame Recommendation
  'step_1_of_5': 'Step 1 of 5',
  'step_2_of_5': 'Step 2 of 5',
  'step_3_of_5': 'Step 3 of 5',
  'step_4_of_5': 'Step 4 of 5',

  'how_old_are_you': 'How old are you?',
  'how_can_we_identify_you': 'How can we identify you?',
  'what_are_you_looking_for': 'What are you looking for?',

  // Lens Recommendation
  'step_1_of_12': 'Step 1 of 12',
  'step_2_of_12': 'Step 2 of 12',
  'step_3_of_12': 'Step 3 of 12',
  'step_4_of_12': 'Step 4 of 12',
  'step_5_of_12': 'Step 5 of 12',
  'step_6_of_12': 'Step 6 of 12',
  'step_7_of_12': 'Step 7 of 12',
  'step_8_of_12': 'Step 8 of 12',
  'step_9_of_12': 'Step 9 of 12',
  'step_10_of_12': 'Step 10 of 12',
  'step_11_of_12': 'Step 11 of 12',
  'step_12_of_12': 'Step 12 of 12',
  
  'have_prescription_before': 'Have you worn any kind of prescription before?',
  'what_best_describes_your_main_daily_visual_activity': 'What best describes your main daily visual activity?',
  'how_many_hours_per_day_do_you_use_your_eyes_intensively': 'How many hours per day do you use your eyes intensively?',
  'how_often_do_you_switch_focus_or_environment_during_the_day': 'How often do you switch focus or environment during the day?',
  'what_best_describes_your_typical_environment': 'What best describes your typical environment?',
  
  // Privacy Intro
  'privacy_intro_title': "You're about to use a privacy-friendly virtual try-on service",
  'privacy_intro_subtitle': "We'll detect generic points on your face, and that's it!",
  'no_facial_recognition': 'No facial recognition or identification',
  'no_storage_sharing': 'No storage or sharing of your image',
  'read_privacy_policy': 'Please read our privacy policy before accessing the service',
  'agree_continue': 'Agree & Continue',
  'encrypted': 'Encrypted',
  'private': 'Private',
  
  // Scan Face Screen
  'scan_face_instruction': 'We will measure your face shapes, skin tone, and eye measurements first!',
  'analyzing_face': 'Analyzing your beautiful face!',
  'start_scanning': 'Start Scanning',
  'scanning': 'Scanning...',
  
  // Scan Result Screen
  'analyze_completed': 'Analyze completed!',
  'face_profile': 'Face Profile',
  'face_shape': 'Face Shape',
  'skin_tone': 'Skin tone',
  'measurement': 'Measurement',
  'face_width': 'Face Width',
  'eye_length': 'Eye Length',
  'eye_width': 'Eye Width',
  'eye_height': 'Eye Height',
  'bridge': 'Bridge',
  'temple_length': 'Temple Length',
  'perfect_match': 'Perfect Match',
  'frame': 'Frame',
  'color': 'Color',
  'retake_scan': 'Retake Scan',
  'try_on_myself': 'Try on Myself',
  
  // Sync Information Screen
  'store_information': 'Store Information',
  'store': 'Store',
  'store_address': 'Store Address',
  'store_phone': 'Store Phone',
  'last_updated': 'Last Updated',
  'current_time': 'Current Time',
  'logout': 'Logout',
  'continue': 'Continue',
};